
import {
  Smartphone,
  Heart,
  Headphones,
  Shirt,
  Home,
  Car,
  Book,
  Gamepad2,
  Laptop,
  Watch,
} from "lucide-react";

 export const categories = [
    {
      id: "smartphones",
      name: "Smartphones",
      icon: Smartphone,
      gradient: "from-blue-500 to-cyan-400",
      bgColor: "bg-blue-50",
      hoverColor: "hover:bg-blue-100",
    },
    {
      id: "skin-care",
      name: "Beauty",
      icon: Heart,
      gradient: "from-pink-500 to-rose-400",
      bgColor: "bg-pink-50",
      hoverColor: "hover:bg-pink-100",
    },
    {
      id: "mobile-accessories",
      name: "Accessories",
      icon: Headphones,
      gradient: "from-purple-500 to-indigo-400",
      bgColor: "bg-purple-50",
      hoverColor: "hover:bg-purple-100",
    },
    {
      id: "mens-shirts",
      name: "Fashion",
      icon: Shirt,
      gradient: "from-emerald-500 to-teal-400",
      bgColor: "bg-emerald-50",
      hoverColor: "hover:bg-emerald-100",
    },
    {
      id: "home-decoration",
      name: "Home & Decor",
      icon: Home,
      gradient: "from-amber-500 to-orange-400",
      bgColor: "bg-amber-50",
      hoverColor: "hover:bg-amber-100",
    },
    {
      id: "motorcycle",
      name: "Automotive",
      icon: Car,
      gradient: "from-slate-600 to-gray-600",
      bgColor: "bg-slate-50",
      hoverColor: "hover:bg-slate-100",
    },
    {
      id: "books",
      name: "Books",
      icon: Book,
      gradient: "from-red-500 to-pink-400",
      bgColor: "bg-red-50",
      hoverColor: "hover:bg-red-100",
    },
    {
      id: "sports-accessories",
      name: "Gaming",
      icon: Gamepad2,
      gradient: "from-violet-500 to-purple-500",
      bgColor: "bg-violet-50",
      hoverColor: "hover:bg-violet-100",
    },
    {
      id: "laptops",
      name: "Electronics",
      icon: Laptop,
      gradient: "from-cyan-500 to-blue-500",
      bgColor: "bg-cyan-50",
      hoverColor: "hover:bg-cyan-100",
    },
    {
      id: "womens-watches",
      name: "Watches",
      icon: Watch,
      gradient: "from-gray-600 to-slate-600",
      bgColor: "bg-gray-50",
      hoverColor: "hover:bg-gray-100",
    },
  ];